0:
  menu_header: "|   MENU   |"
  menu_border: "+==========+"
  menu_context: "| Task 182 |\n| Task 323 |\n| Task 560 |"
  enter_message: "Enter task number: "
  incorrect_option_message: "Incorrect option! "
  choose_another_option_message: "Do you want to continue? [Y/n]: "
  app_exit_message: "App exit "
  invalid_data_entered_message: "Entered numbers must be greater then zero, not double and not a string! "

182:
  task_name: "|Task 182|"
  task_description: "Find the sum and the number of those members of this sequence, which are divided by 5 and do not divide by 7. "
  input_data:
    natural_number: "Enter count numbers in sequence: "
  output_data:
    sequence_numbers: "Sequence numbers: "
    sequence_sum: "Sum of correct numbers from sequence = "
    sequence_count: "Count of correct numbers from sequence = "

323:
  task_name: "|Task 323|"
  task_description: "Get all natural numbers that are smaller for the number n and are relatively prime to it. "
  input_data:
    natural_number: "Enter natural number: "
  output_data:
    sequence_numbers: "All mutually simple numbers: "

560:
  task_name: "|Task 560|"
  task_description: "Find all pairs of friendly numbers lying in the entered range. "
  input_data:
    start_number: "Enter start number : "
    end_number: "Enter end number : "
  output_data:
    sequence_numbers: "All pairs of friendly numbers: "


